#!/bin/sh
echo MKLINUX: loading ramdisk...
./copy_ramdisk 0x60000000
echo MKLINUX: setting boot arguments...
./set_boot_args
echo MKLINUX: loading kernel...
kexec -d -l /kernel/vmlinux.elf -t elf-x86 --args-none
echo MKLINUX: booting kernel...
kexec -d -b 3

